### ISSUE TITLE
Add check for Consistent read

### ISSUE THREAD

**Issue by maximecaron** [michaelbironneau/go-agree#2]
In order to have consistent read, read request need to be forwarded to leader node.
Also leader node need to verify it is still the leader using the code below.

if err := raft.VerifyLeader().Error(); err != nil {
            return err
}

**Comment by michaelbironneau** [comment]
You're right. Going forward I'll make the read consistency configurable along the same lines as suggested in the OP on a similar issue in etcd (see [here](https://github.com/coreos/etcd/issues/741)). This will mean that the user can opt for consistent reads or potentially stale reads.

**Comment by michaelbironneau** [comment]
Resolved by db4aec0ff81b376d8044b0c0a927cc45802f4a2f. The leader now verifies that it is still the leader before accepting any writes and reads now have three consistency options: "Any" (potentially stale but faster), "Leader" (no network round trip done to verify it is still leader) and "Consistent", which means that the read is done via Raft leader which checks it is still the leader before replying.
